spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  application:
    name: firstPrj
  datasource:
    url: jdbc:mysql://203.245.30.178:3307/cnn
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2718
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sejong.firstPrj.entity