create table GUESTBOOK (
    GUESTBOOK_ID INT         NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    REGISTER     DATETIME    NOT NULL,
    NAME         VARCHAR(20) NOT NULL,
    EMAIL        VARCHAR(40) NOT NULL,
    PASSWORD     VARCHAR(10),
    CONTENT      MEDIUMTEXT  NOT NULL
)
